; G139 formal-logic Registry slice. Token recognition and domain admission
; are separate: every row requires an explicit formal-profile gate.
bits 64
default rel

%include "compiler/tokens/token_kind.inc"
%include "compiler/tokens/operator_registry.inc"
%include "compiler/parser/expression/operator_precedence.inc"

%define FORMAL_ID 0
%define FORMAL_TOKEN 8
%define FORMAL_FIXITY 16
%define FORMAL_PRECEDENCE 24
%define FORMAL_ASSOC 32
%define FORMAL_FLAGS 40
%define FORMAL_ENTRY_SIZE 48
%define FORMAL_ENTRY_COUNT 9

section .rodata
align 8
formal_entries:
 dq NEBOC_OPERATOR_ID_NSR_DOM_061,NEBOC_TOKEN_FOR_ALL,NEBOC_OPERATOR_PARSE_FIXITY_BINDER,NEBOC_OPERATOR_BP_PREFIX,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_062,NEBOC_TOKEN_EXISTS,NEBOC_OPERATOR_PARSE_FIXITY_BINDER,NEBOC_OPERATOR_BP_PREFIX,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_063,NEBOC_TOKEN_NOT_EXISTS,NEBOC_OPERATOR_PARSE_FIXITY_BINDER,NEBOC_OPERATOR_BP_PREFIX,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_064,NEBOC_TOKEN_LOGIC_IMPLIES,NEBOC_OPERATOR_PARSE_FIXITY_INFIX,NEBOC_OPERATOR_BP_IMPLICATION,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_065,NEBOC_TOKEN_LOGIC_IFF,NEBOC_OPERATOR_PARSE_FIXITY_INFIX,NEBOC_OPERATOR_BP_EQUIVALENCE,NEBOC_OPERATOR_PARSE_ASSOC_NONASSOC,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_NONASSOCIATIVE|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_066,NEBOC_TOKEN_PROVES,NEBOC_OPERATOR_PARSE_FIXITY_CONTEXTUAL,0,NEBOC_OPERATOR_PARSE_ASSOC_NONE,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_067,NEBOC_TOKEN_SATISFIES,NEBOC_OPERATOR_PARSE_FIXITY_CONTEXTUAL,0,NEBOC_OPERATOR_PARSE_ASSOC_NONE,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_068,NEBOC_TOKEN_LOGIC_NAND,NEBOC_OPERATOR_PARSE_FIXITY_INFIX,NEBOC_OPERATOR_BP_AND,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_OPERATOR_ID_NSR_DOM_069,NEBOC_TOKEN_LOGIC_NOR,NEBOC_OPERATOR_PARSE_FIXITY_INFIX,NEBOC_OPERATOR_BP_OR,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED

section .text
global nebo_formal_logic_operator_plan, nebo_formal_logic_registry_lookup

; edi=zero-based row, esi=formal domain gate. eax=0 admitted, 1 gate, 2 row.
; On admission RDX is the immutable Registry row.
nebo_formal_logic_operator_plan:
 test esi,esi
 jz .gate
 cmp edi,FORMAL_ENTRY_COUNT-1
 ja .row
 mov eax,edi
 imul rax,FORMAL_ENTRY_SIZE
 lea rdx,[rel formal_entries]
 add rdx,rax
 xor eax,eax
 ret
.gate:
 mov eax,1
 xor edx,edx
 ret
.row:
 mov eax,2
 xor edx,edx
 ret

; rdi=Registry ID, rsi=formal gate. RAX=row or zero; output fields mirror row.
nebo_formal_logic_registry_lookup:
 test rsi,rsi
 jz .miss
 lea rax,[rel formal_entries]
 mov r11d,FORMAL_ENTRY_COUNT
.loop:
 cmp [rax+FORMAL_ID],rdi
 je .found
 add rax,FORMAL_ENTRY_SIZE
 dec r11d
 jnz .loop
.miss:
 xor eax,eax
 xor edx,edx
 xor ecx,ecx
 xor r8d,r8d
 xor r9d,r9d
 xor r10d,r10d
 ret
.found:
 mov edx,[rax+FORMAL_TOKEN]
 mov ecx,[rax+FORMAL_FIXITY]
 mov r8d,[rax+FORMAL_PRECEDENCE]
 mov r9d,[rax+FORMAL_ASSOC]
 mov r10d,[rax+FORMAL_FLAGS]
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
