; Arithmetic-family classifier shared by parser conformance and tooling.
bits 64
default rel

%include "compiler/abi/internal/x86_64/neboc_internal_abi.inc"
%include "compiler/tokens/token_kind.inc"
%include "compiler/parser/expression/operator_precedence.inc"

%define ARITHMETIC_TOKEN_OFFSET 0
%define ARITHMETIC_REGISTRY_ID_OFFSET 8
%define ARITHMETIC_FAMILY_OFFSET 16
%define ARITHMETIC_LEFT_BP_OFFSET 24
%define ARITHMETIC_RIGHT_BP_OFFSET 32
%define ARITHMETIC_ASSOC_OFFSET 40
%define ARITHMETIC_FLAGS_OFFSET 48
%define ARITHMETIC_ENTRY_SIZE 56
%define ARITHMETIC_ENTRY_COUNT 5

section .rodata
align 8
arithmetic_entries:
 dq NEBOC_TOKEN_PLUS,12,NEBOC_OPERATOR_FAMILY_ADDITIVE,NEBOC_OPERATOR_BP_ADDITIVE,NEBOC_OPERATOR_BP_ADDITIVE+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT
 dq NEBOC_TOKEN_MINUS,13,NEBOC_OPERATOR_FAMILY_ADDITIVE,NEBOC_OPERATOR_BP_ADDITIVE,NEBOC_OPERATOR_BP_ADDITIVE+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT
 dq NEBOC_TOKEN_STAR,14,NEBOC_OPERATOR_FAMILY_MULTIPLICATIVE,NEBOC_OPERATOR_BP_MULTIPLICATIVE,NEBOC_OPERATOR_BP_MULTIPLICATIVE+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT
 dq NEBOC_TOKEN_SLASH,15,NEBOC_OPERATOR_FAMILY_MULTIPLICATIVE,NEBOC_OPERATOR_BP_MULTIPLICATIVE,NEBOC_OPERATOR_BP_MULTIPLICATIVE+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT
 dq NEBOC_TOKEN_PERCENT,16,NEBOC_OPERATOR_FAMILY_MULTIPLICATIVE,NEBOC_OPERATOR_BP_MULTIPLICATIVE,NEBOC_OPERATOR_BP_MULTIPLICATIVE+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT

section .text
; arithmetic_lookup(token_kind) -> RAX=record or zero; EDX=Registry ID,
; ECX=family, R8D=left BP, R9D=right BP, R10D=flags.
NEBOC_ABI_FUNCTION neboc_operator_arithmetic_lookup
 lea rax,[rel arithmetic_entries]
 mov r11d,ARITHMETIC_ENTRY_COUNT
.loop:
 cmp [rax+ARITHMETIC_TOKEN_OFFSET],rdi
 je .found
 add rax,ARITHMETIC_ENTRY_SIZE
 dec r11d
 jnz .loop
 xor eax,eax
 xor edx,edx
 xor ecx,ecx
 xor r8d,r8d
 xor r9d,r9d
 xor r10d,r10d
 ret
.found:
 mov edx,[rax+ARITHMETIC_REGISTRY_ID_OFFSET]
 mov ecx,[rax+ARITHMETIC_FAMILY_OFFSET]
 mov r8d,[rax+ARITHMETIC_LEFT_BP_OFFSET]
 mov r9d,[rax+ARITHMETIC_RIGHT_BP_OFFSET]
 mov r10d,[rax+ARITHMETIC_FLAGS_OFFSET]
 ret

; Domain composition is architecturally assigned P145/right, but P01 cannot
; recognize or activate a lexeme for it.
NEBOC_ABI_FUNCTION neboc_operator_composition_contract
 xor eax,eax
 mov edx,NEBOC_OPERATOR_FAMILY_COMPOSITION
 mov ecx,NEBOC_OPERATOR_BP_COMPOSITION
 mov r8d,NEBOC_OPERATOR_BP_COMPOSITION
 mov r9d,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT
 mov r10d,NEBOC_OPERATOR_PARSE_FLAG_INACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
