; Registry-classified suffix forms. This module classifies; Pratt remains the
; single parser and must reject rows marked inactive or domain-gated.
bits 64
default rel

%include "compiler/abi/internal/x86_64/neboc_internal_abi.inc"
%include "compiler/tokens/token_kind.inc"
%include "compiler/parser/expression/operator_precedence.inc"

%define NEBOC_OPERATOR_SUFFIX_MEMBER_FLOW_BINDING 1
%define NEBOC_OPERATOR_SUFFIX_CALL 2
%define NEBOC_OPERATOR_SUFFIX_INDEX 3
%define NEBOC_OPERATOR_SUFFIX_PERCENT 4
%define NEBOC_OPERATOR_SUFFIX_FACTORIAL 5
%define NEBOC_OPERATOR_SUFFIX_RESULT_PROPAGATE 6
%define NEBOC_OPERATOR_SUFFIX_OPTIONAL_CHAIN 7

%define SUFFIX_TOKEN_OFFSET 0
%define SUFFIX_ACTION_OFFSET 8
%define SUFFIX_LEFT_BP_OFFSET 16
%define SUFFIX_RIGHT_BP_OFFSET 24
%define SUFFIX_ASSOC_OFFSET 32
%define SUFFIX_FLAGS_OFFSET 40
%define SUFFIX_ENTRY_SIZE 48
%define SUFFIX_ENTRY_COUNT 7

section .rodata
align 8
suffix_entries:
 dq NEBOC_TOKEN_DOT,NEBOC_OPERATOR_SUFFIX_MEMBER_FLOW_BINDING,NEBOC_OPERATOR_BP_SUFFIX,NEBOC_OPERATOR_BP_SUFFIX+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL
 dq NEBOC_TOKEN_LPAREN,NEBOC_OPERATOR_SUFFIX_CALL,NEBOC_OPERATOR_BP_SUFFIX,NEBOC_OPERATOR_BP_SUFFIX+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL
 dq NEBOC_TOKEN_RESERVED_LBRACKET,NEBOC_OPERATOR_SUFFIX_INDEX,NEBOC_OPERATOR_BP_SUFFIX,NEBOC_OPERATOR_BP_SUFFIX+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_INACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL
 dq NEBOC_TOKEN_PERCENT,NEBOC_OPERATOR_SUFFIX_PERCENT,NEBOC_OPERATOR_BP_POSTFIX,NEBOC_OPERATOR_BP_POSTFIX+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_INACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL
 dq NEBOC_TOKEN_BANG,NEBOC_OPERATOR_SUFFIX_FACTORIAL,NEBOC_OPERATOR_BP_POSTFIX,NEBOC_OPERATOR_BP_POSTFIX+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_INACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED
 dq NEBOC_TOKEN_QUESTION,NEBOC_OPERATOR_SUFFIX_RESULT_PROPAGATE,NEBOC_OPERATOR_BP_POSTFIX,NEBOC_OPERATOR_BP_POSTFIX+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL|NEBOC_OPERATOR_PARSE_FLAG_SHORT_CIRCUIT
 dq NEBOC_TOKEN_OPTIONAL_CHAIN,NEBOC_OPERATOR_SUFFIX_OPTIONAL_CHAIN,NEBOC_OPERATOR_BP_SUFFIX,NEBOC_OPERATOR_BP_SUFFIX+1,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL|NEBOC_OPERATOR_PARSE_FLAG_SHORT_CIRCUIT

section .text
; suffix_lookup(token_kind) -> RAX=record or zero, EDX=action, ECX=left BP,
; R8D=right BP, R9D=associativity, R10D=activation flags.
NEBOC_ABI_FUNCTION neboc_operator_suffix_lookup
 lea rax,[rel suffix_entries]
 mov r11d,SUFFIX_ENTRY_COUNT
.loop:
 cmp [rax+SUFFIX_TOKEN_OFFSET],rdi
 je .found
 add rax,SUFFIX_ENTRY_SIZE
 dec r11d
 jnz .loop
 xor eax,eax
 xor edx,edx
 xor ecx,ecx
 xor r8d,r8d
 xor r9d,r9d
 xor r10d,r10d
 ret
.found:
 mov edx,[rax+SUFFIX_ACTION_OFFSET]
 mov ecx,[rax+SUFFIX_LEFT_BP_OFFSET]
 mov r8d,[rax+SUFFIX_RIGHT_BP_OFFSET]
 mov r9d,[rax+SUFFIX_ASSOC_OFFSET]
 mov r10d,[rax+SUFFIX_FLAGS_OFFSET]
 ret

NEBOC_ABI_FUNCTION neboc_operator_suffix_table
 lea rax,[rel suffix_entries]
 mov edx,SUFFIX_ENTRY_COUNT
 mov ecx,SUFFIX_ENTRY_SIZE
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
