; Logical, coalescing and assignment family contracts on one precedence scale.
bits 64
default rel

%include "compiler/abi/internal/x86_64/neboc_internal_abi.inc"
%include "compiler/tokens/token_kind.inc"
%include "compiler/tokens/operator_registry.inc"
%include "compiler/parser/expression/operator_precedence.inc"

%define LOGIC_FAMILY_OFFSET 0
%define LOGIC_BP_OFFSET 8
%define LOGIC_ASSOC_OFFSET 16
%define LOGIC_FLAGS_OFFSET 24
%define LOGIC_TOKEN_OFFSET 32
%define LOGIC_REGISTRY_ID_OFFSET 40
%define LOGIC_ENTRY_SIZE 48
%define LOGIC_ENTRY_COUNT 9

section .rodata
align 8
logic_entries:
 dq NEBOC_OPERATOR_FAMILY_XOR,NEBOC_OPERATOR_BP_XOR,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT,NEBOC_TOKEN_XOR,23
 dq NEBOC_OPERATOR_FAMILY_AND,NEBOC_OPERATOR_BP_AND,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_SHORT_CIRCUIT,NEBOC_TOKEN_AND_AND,21
 dq NEBOC_OPERATOR_FAMILY_OR,NEBOC_OPERATOR_BP_OR,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_SHORT_CIRCUIT,NEBOC_TOKEN_OR_OR,22
 dq NEBOC_OPERATOR_FAMILY_IMPLICATION,NEBOC_OPERATOR_BP_IMPLICATION,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED,NEBOC_TOKEN_LOGIC_IMPLIES,NEBOC_OPERATOR_ID_NSR_DOM_064
 dq NEBOC_OPERATOR_FAMILY_EQUIVALENCE,NEBOC_OPERATOR_BP_EQUIVALENCE,NEBOC_OPERATOR_PARSE_ASSOC_NONASSOC,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED|NEBOC_OPERATOR_PARSE_FLAG_NONASSOCIATIVE,NEBOC_TOKEN_LOGIC_IFF,NEBOC_OPERATOR_ID_NSR_DOM_065
 dq NEBOC_OPERATOR_FAMILY_AND,NEBOC_OPERATOR_BP_AND,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED,NEBOC_TOKEN_LOGIC_NAND,NEBOC_OPERATOR_ID_NSR_DOM_068
 dq NEBOC_OPERATOR_FAMILY_OR,NEBOC_OPERATOR_BP_OR,NEBOC_OPERATOR_PARSE_ASSOC_LEFT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_DOMAIN_GATE_REQUIRED,NEBOC_TOKEN_LOGIC_NOR,NEBOC_OPERATOR_ID_NSR_DOM_069
 dq NEBOC_OPERATOR_FAMILY_COALESCE,NEBOC_OPERATOR_BP_COALESCE,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT,NEBOC_OPERATOR_PARSE_FLAG_ACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_SHORT_CIRCUIT,NEBOC_TOKEN_COALESCE,39
 dq NEBOC_OPERATOR_FAMILY_ASSIGNMENT,NEBOC_OPERATOR_BP_ASSIGNMENT,NEBOC_OPERATOR_PARSE_ASSOC_RIGHT,NEBOC_OPERATOR_PARSE_FLAG_INACTIVE_CURRENT|NEBOC_OPERATOR_PARSE_FLAG_CONTEXTUAL,NEBOC_TOKEN_RESERVED_EQUAL,31

section .text
; logic_family_lookup(family) -> RAX=record or zero; EDX=BP,
; ECX=associativity, R8D=flags, R9D=token kind, R10=full-width Registry ID.
NEBOC_ABI_FUNCTION neboc_operator_logic_family_lookup
 lea rax,[rel logic_entries]
 mov r11d,LOGIC_ENTRY_COUNT
.loop:
 cmp [rax+LOGIC_FAMILY_OFFSET],rdi
 je .found
 add rax,LOGIC_ENTRY_SIZE
 dec r11d
 jnz .loop
 xor eax,eax
 xor edx,edx
 xor ecx,ecx
 xor r8d,r8d
 xor r9d,r9d
 xor r10d,r10d
 ret
.found:
 mov edx,[rax+LOGIC_BP_OFFSET]
 mov ecx,[rax+LOGIC_ASSOC_OFFSET]
 mov r8d,[rax+LOGIC_FLAGS_OFFSET]
 mov r9d,[rax+LOGIC_TOKEN_OFFSET]
 mov r10,[rax+LOGIC_REGISTRY_ID_OFFSET]
 ret

; Token lookup never treats INVALID (zero) as an active surface.
NEBOC_ABI_FUNCTION neboc_operator_logic_token_lookup
 test rdi,rdi
 jz .token_miss
 lea rax,[rel logic_entries]
 mov r11d,LOGIC_ENTRY_COUNT
.token_loop:
 cmp [rax+LOGIC_TOKEN_OFFSET],rdi
 je .token_found
 add rax,LOGIC_ENTRY_SIZE
 dec r11d
 jnz .token_loop
.token_miss:
 xor eax,eax
 xor edx,edx
 xor ecx,ecx
 ret
.token_found:
 mov edx,[rax+LOGIC_FAMILY_OFFSET]
 mov ecx,[rax+LOGIC_FLAGS_OFFSET]
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
