%define G072_FEATURE_ID 7202
%define G072_TARGET_TOKEN RENDER_TARGET_TOKEN_VISUAL
%define G072_TARGET_AUX RENDER_VISUAL_TEXT|RENDER_VISUAL_CONTRAST
%include "tests/rf84/rf84-g72/target_front_test.inc"
