bits 64
default rel
%include "runtime/textual/text_core.inc"

extern neboc_text_error_diagnostic
extern neboc_text_limit_check

section .text
%macro CHECK_DIAGNOSTIC 2
 mov edi,%1
 call neboc_text_error_diagnostic
 cmp eax,%2
 jne fail
%endmacro

global _start
_start:
 xor edi,edi
 call neboc_text_error_diagnostic
 test eax,eax
 jnz fail

 CHECK_DIAGNOSTIC NEBO_TEXT_ERROR_INVALID_BYTE_INDEX,NEBO_DIAG_TEXT_INVALID_BYTE_INDEX
 CHECK_DIAGNOSTIC NEBO_TEXT_ERROR_INVALID_UTF8,NEBO_DIAG_TEXT_UTF8
 CHECK_DIAGNOSTIC NEBO_TEXT_ERROR_INVALID_RANGE,NEBO_DIAG_TEXT_INVALID_RANGE
 CHECK_DIAGNOSTIC NEBO_TEXT_ERROR_EMPTY_SEPARATOR,NEBO_DIAG_TEXT_EMPTY_SEPARATOR
 CHECK_DIAGNOSTIC NEBO_TEXT_ERROR_ALLOCATION_FAILED,NEBO_DIAG_TEXT_CAPACITY
 CHECK_DIAGNOSTIC NEBO_TEXT_ERROR_UNSUPPORTED_UNICODE_PROFILE,NEBO_DIAG_TEXT_POLICY
 CHECK_DIAGNOSTIC NEBO_TEXT_PARSE_ERROR_EMPTY_INPUT,NEBO_DIAG_TEXT_PARSE_EMPTY_INPUT
 CHECK_DIAGNOSTIC NEBO_TEXT_PARSE_ERROR_INVALID_DIGIT,NEBO_DIAG_TEXT_PARSE_INVALID_DIGIT
 CHECK_DIAGNOSTIC NEBO_TEXT_PARSE_ERROR_OVERFLOW,NEBO_DIAG_TEXT_PARSE_OVERFLOW
 CHECK_DIAGNOSTIC NEBO_TEXT_PARSE_ERROR_UNDERFLOW,NEBO_DIAG_TEXT_PARSE_UNDERFLOW
 CHECK_DIAGNOSTIC NEBO_TEXT_PARSE_ERROR_INVALID_BOOLEAN,NEBO_DIAG_TEXT_PARSE_INVALID_BOOLEAN
 CHECK_DIAGNOSTIC NEBO_TEXT_PARSE_ERROR_TRAILING_CHARACTERS,NEBO_DIAG_TEXT_PARSE_TRAILING_CHARACTERS
 CHECK_DIAGNOSTIC NEBO_TEXT_PARSE_ERROR_UNSUPPORTED_FORMAT,NEBO_DIAG_TEXT_PARSE_UNSUPPORTED_FORMAT

 mov edi,99
 call neboc_text_error_diagnostic
 test eax,eax
 jnz fail
 mov edi,MAX_TEXT_BYTES
 mov esi,NEBO_TEXT_LIMIT_BUILDER_BYTES
 call neboc_text_limit_check
 test eax,eax
 jnz fail
 mov rdi,MAX_TEXT_BYTES+1
 xor esi,esi
 call neboc_text_limit_check
 cmp eax,NEBO_TEXT_ERROR_ALLOCATION_FAILED
 jne fail
 xor edi,edi
 mov rsi,NEBO_TEXT_LIMIT_BUILDER_BYTES+1
 call neboc_text_limit_check
 cmp eax,NEBO_TEXT_ERROR_ALLOCATION_FAILED
 jne fail

 xor edi,edi
 mov eax,60
 syscall
fail:
 mov edi,7
 mov eax,60
 syscall
section .note.GNU-stack noalloc noexec nowrite progbits
