; G144 compiled projection of NSR-RES-001..023.  The canonical spelling rows
; remain in the Symbol and Operator Registry TSV; this table publishes the
; immutable class/state/token/diagnostic contract consumed by compiler tools.
bits 64
default rel

%include "compiler/abi/internal/x86_64/neboc_internal_abi.inc"
%include "compiler/support/status/status_codes.inc"
%include "compiler/tokens/token_kind.inc"
%include "compiler/tokens/operator_registry.inc"
%include "compiler/lexer/lexer.inc"
%include "compiler/diagnostics/reserved/symbol_registry.inc"

section .rodata align=8
reserved_symbol_entries:
%macro RESERVED_SYMBOL_ROW 3
 dq %1,%2,NEBOC_OPERATOR_CLASS_RESERVED
 dq %3,NEBOC_TOKEN_RESERVED_SYMBOL
 dq NEBOC_LEX_DIAG_RESERVED_SYMBOL,0
%endmacro
 RESERVED_SYMBOL_ROW 1,NEBOC_OPERATOR_ID_NSR_RES_001,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 2,NEBOC_OPERATOR_ID_NSR_RES_002,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 3,NEBOC_OPERATOR_ID_NSR_RES_003,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 4,NEBOC_OPERATOR_ID_NSR_RES_004,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 5,NEBOC_OPERATOR_ID_NSR_RES_005,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 6,NEBOC_OPERATOR_ID_NSR_RES_006,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 7,NEBOC_OPERATOR_ID_NSR_RES_007,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 8,NEBOC_OPERATOR_ID_NSR_RES_008,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 9,NEBOC_OPERATOR_ID_NSR_RES_009,NEBOC_OPERATOR_STATE_UNSUPPORTED_CURRENT
 RESERVED_SYMBOL_ROW 10,NEBOC_OPERATOR_ID_NSR_RES_010,NEBOC_OPERATOR_STATE_METHOD_ACTIVE_SYMBOL_INACTIVE
 RESERVED_SYMBOL_ROW 11,NEBOC_OPERATOR_ID_NSR_RES_011,NEBOC_OPERATOR_STATE_METHOD_ACTIVE_SYMBOL_INACTIVE
 RESERVED_SYMBOL_ROW 12,NEBOC_OPERATOR_ID_NSR_RES_012,NEBOC_OPERATOR_STATE_METHOD_ACTIVE_SYMBOL_INACTIVE
 RESERVED_SYMBOL_ROW 13,NEBOC_OPERATOR_ID_NSR_RES_013,NEBOC_OPERATOR_STATE_METHOD_ACTIVE_SYMBOL_INACTIVE
 RESERVED_SYMBOL_ROW 14,NEBOC_OPERATOR_ID_NSR_RES_014,NEBOC_OPERATOR_STATE_METHOD_ACTIVE_SYMBOL_INACTIVE
 RESERVED_SYMBOL_ROW 15,NEBOC_OPERATOR_ID_NSR_RES_015,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT_USE_AT
 RESERVED_SYMBOL_ROW 16,NEBOC_OPERATOR_ID_NSR_RES_016,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 17,NEBOC_OPERATOR_ID_NSR_RES_017,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 18,NEBOC_OPERATOR_ID_NSR_RES_018,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 19,NEBOC_OPERATOR_ID_NSR_RES_019,NEBOC_OPERATOR_STATE_CALLABLE_SUBSTRATE_ACTIVE_SYMBOL_INACTIVE
 RESERVED_SYMBOL_ROW 20,NEBOC_OPERATOR_ID_NSR_RES_020,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 21,NEBOC_OPERATOR_ID_NSR_RES_021,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 22,NEBOC_OPERATOR_ID_NSR_RES_022,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
 RESERVED_SYMBOL_ROW 23,NEBOC_OPERATOR_ID_NSR_RES_023,NEBOC_OPERATOR_STATE_INACTIVE_CURRENT
%undef RESERVED_SYMBOL_ROW

section .text
; Returns RAX=entries, EDX=count, ECX=entry size.
NEBOC_ABI_FUNCTION neboc_reserved_symbol_registry_table
 lea rax,[rel reserved_symbol_entries]
 mov edx,NEBOC_RESERVED_SYMBOL_COUNT
 mov ecx,NEBOC_RESERVED_SYMBOL_ENTRY_SIZE
 ret

; reserved_symbol_metadata(ordinal, out*) -> StatusCode.  Invalid input leaves
; the caller's output untouched, which makes tooling failure atomic.
NEBOC_ABI_FUNCTION neboc_reserved_symbol_metadata
 test rsi,rsi
 jz .invalid
 test rdi,rdi
 jz .source
 cmp rdi,NEBOC_RESERVED_SYMBOL_COUNT
 ja .source
 dec rdi
 imul rdi,NEBOC_RESERVED_SYMBOL_ENTRY_SIZE
 lea r8,[rel reserved_symbol_entries]
 add r8,rdi
 mov rax,[r8]
 mov rdx,[r8+8]
 mov rcx,[r8+16]
 mov r9,[r8+24]
 mov r10,[r8+32]
 mov r11,[r8+40]
 mov [rsi],rax
 mov [rsi+8],rdx
 mov [rsi+16],rcx
 mov [rsi+24],r9
 mov [rsi+32],r10
 mov [rsi+40],r11
 mov qword [rsi+48],0
 xor eax,eax
 ret
.source:
 mov eax,NEBOC_STATUS_INVALID_SOURCE
 ret
.invalid:
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
