%define G071_FEATURE_ID 7104
%define G071_POLICY_TOKEN RENDER_POLICY_ACCESSIBILITY
%define G071_POLICY_AUX RENDER_ACCESS_TEXT|RENDER_ACCESS_HIGH_CONTRAST
%include "tests/rf84/rf84-g71/policy_front_test.inc"
