; BINDINGS-CONSTANTES-MUTABILIDADE-E-DEFINITE-ASSIGNMENT-PF002 binding syntax/API/diagnostic contract tests
bits 64
default rel
%include "compiler/support/status/status_codes.inc"
%include "compiler/parser/binding_definite_assignment_contract.inc"
extern neboc_binding_contract
extern neboc_host_process_exit

section .rodata
n_counter: db "counter"
n_name: db "name"
n_ready: db "ready"
n_value: db "value"
n_start: db "start"
n_bad: db "1bad"
%macro CASE 12
 dq %1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12
%endmacro
section .data align=8
cases:
 CASE NEBOC_BIND_OP_DIRECT_BINDING,0,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_value,5,NEBOC_STATUS_OK,NEBOC_BIND_AST_BINDING_TERMINAL,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_DIRECT_BINDING,0,NEBOC_BIND_TYPE_TEXT,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_name,4,NEBOC_STATUS_OK,NEBOC_BIND_AST_BINDING_TERMINAL,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_TYPED_DECLARATION,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_OK,NEBOC_BIND_AST_TYPED_DECLARATION,NEBOC_BIND_STATE_DECLARED_UNINITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_TYPED_DECLARATION,NEBOC_BIND_TYPE_BOOL,0,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_ready,5,NEBOC_STATUS_OK,NEBOC_BIND_AST_TYPED_DECLARATION,NEBOC_BIND_STATE_DECLARED_UNINITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_TYPED_DECLARATION,NEBOC_BIND_TYPE_CHAR,0,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_value,5,NEBOC_STATUS_OK,NEBOC_BIND_AST_TYPED_DECLARATION,NEBOC_BIND_STATE_DECLARED_UNINITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_ONE_SHOT_INITIALIZATION,NEBOC_BIND_TYPE_INT,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_DECLARED_UNINITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_OK,NEBOC_BIND_AST_ONE_SHOT_INITIALIZATION,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_ONE_SHOT_INITIALIZATION,NEBOC_BIND_TYPE_TEXT,NEBOC_BIND_TYPE_TEXT,NEBOC_BIND_STATE_DECLARED_UNINITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_name,4,NEBOC_STATUS_OK,NEBOC_BIND_AST_ONE_SHOT_INITIALIZATION,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_READ,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_OK,NEBOC_BIND_AST_IDENTIFIER_READ,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_DEFINITE_READ,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME|NEBOC_BIND_INPUT_ALL_PATHS_INITIALIZED,n_counter,7,NEBOC_STATUS_OK,NEBOC_BIND_AST_IDENTIFIER_READ,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_DIRECT_BINDING,0,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME|NEBOC_BIND_INPUT_EXPLICIT_FORM,n_value,5,NEBOC_STATUS_OK,NEBOC_BIND_AST_BINDING_TERMINAL,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_DIAG_NONE
 CASE NEBOC_BIND_OP_READ,0,0,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_UNDEFINED_NAME
 CASE NEBOC_BIND_OP_READ,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_DECLARED_UNINITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_USE_BEFORE_INITIALIZATION
 CASE NEBOC_BIND_OP_TYPED_DECLARATION,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_DUPLICATE_DECLARATION
 CASE NEBOC_BIND_OP_DIRECT_BINDING,0,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_value,5,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_DUPLICATE_DECLARATION
 CASE NEBOC_BIND_OP_ONE_SHOT_INITIALIZATION,NEBOC_BIND_TYPE_INT,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_ALREADY_INITIALIZED
 CASE NEBOC_BIND_OP_TYPED_DECLARATION,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_PARENT,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_SHADOWING_FORBIDDEN
 CASE NEBOC_BIND_OP_DIRECT_BINDING,0,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME|NEBOC_BIND_INPUT_RESERVED_NAME,n_start,5,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_RESERVED_NAME
 CASE NEBOC_BIND_OP_TYPED_DECLARATION,NEBOC_BIND_TYPE_VOID,0,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_value,5,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_VOID_FORBIDDEN
 CASE NEBOC_BIND_OP_ONE_SHOT_INITIALIZATION,NEBOC_BIND_TYPE_INT,NEBOC_BIND_TYPE_TEXT,NEBOC_BIND_STATE_DECLARED_UNINITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_TYPE_MISMATCH
 CASE NEBOC_BIND_OP_DEFINITE_READ,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_NOT_DEFINITELY_INITIALIZED
 CASE NEBOC_BIND_OP_ASSIGNMENT_SYNTAX,NEBOC_BIND_TYPE_INT,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_INITIALIZED,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_ASSIGNMENT_SYNTAX_UNAVAILABLE
 CASE NEBOC_BIND_OP_CONST_DECLARATION,NEBOC_BIND_TYPE_INT,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_value,5,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_CONST_DECLARATION_DEFERRED
 CASE NEBOC_BIND_OP_MUTABLE_DECLARATION,NEBOC_BIND_TYPE_INT,0,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_counter,7,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_MUTABLE_DECLARATION_DEFERRED
 CASE NEBOC_BIND_OP_NAMED_ARGUMENT,0,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,NEBOC_BIND_INPUT_VALID_NAME,n_value,5,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_NAMED_ARGUMENTS_DEFERRED
 CASE NEBOC_BIND_OP_DIRECT_BINDING,0,NEBOC_BIND_TYPE_INT,NEBOC_BIND_STATE_ABSENT,NEBOC_BIND_SCOPE_SAME,0,n_bad,4,NEBOC_STATUS_INVALID_SOURCE,0,0,NEBOC_BIND_DIAG_INVALID_NAME
case_count equ ($-cases)/(12*8)

section .bss align=16
request: resb NEBOC_BIND_REQUEST_SIZE
first_hash: resq 1
section .text
global _start
_start:
 lea r14,[rel cases]
 mov r15d,case_count
 mov r13d,1
.loop:
 lea rdi,[rel request]
 mov ecx,NEBOC_BIND_REQUEST_SIZE/8
 xor eax,eax
 rep stosq
 mov rax,[r14]
 mov [rel request+NEBOC_BIND_OPERATION_OFFSET],rax
 mov rax,[r14+8]
 mov [rel request+NEBOC_BIND_DECLARED_TYPE_OFFSET],rax
 mov rax,[r14+16]
 mov [rel request+NEBOC_BIND_VALUE_TYPE_OFFSET],rax
 mov rax,[r14+24]
 mov [rel request+NEBOC_BIND_SYMBOL_STATE_OFFSET],rax
 mov rax,[r14+32]
 mov [rel request+NEBOC_BIND_SCOPE_RELATION_OFFSET],rax
 mov rax,[r14+40]
 mov [rel request+NEBOC_BIND_INPUT_FLAGS_OFFSET],rax
 mov rax,[r14+48]
 mov [rel request+NEBOC_BIND_NAME_PTR_OFFSET],rax
 mov rax,[r14+56]
 mov [rel request+NEBOC_BIND_NAME_LENGTH_OFFSET],rax
 mov qword [rel request+NEBOC_BIND_ABSOLUTE_START_OFFSET],700
 lea rdi,[rel request]
 call neboc_binding_contract
 cmp rax,[r14+64]
 jne .fail
 mov rax,[rel request+NEBOC_BIND_AST_FORM_OFFSET]
 cmp rax,[r14+72]
 jne .fail
 mov rax,[rel request+NEBOC_BIND_RESULT_STATE_OFFSET]
 cmp rax,[r14+80]
 jne .fail
 mov rax,[rel request+NEBOC_BIND_DIAGNOSTIC_OFFSET]
 cmp rax,[r14+88]
 jne .fail
 cmp qword [r14+64],NEBOC_STATUS_OK
 je .success_span
 cmp qword [rel request+NEBOC_BIND_ERROR_START_OFFSET],700
 jne .fail
 mov rax,700
 add rax,[r14+56]
 cmp [rel request+NEBOC_BIND_ERROR_END_OFFSET],rax
 jne .fail
 jmp .next
.success_span:
 cmp qword [rel request+NEBOC_BIND_ERROR_START_OFFSET],0
 jne .fail
 cmp qword [rel request+NEBOC_BIND_ERROR_END_OFFSET],0
 jne .fail
.next:
 add r14,96
 inc r13d
 dec r15d
 jnz .loop
 ; deterministic hash for an identical request
 lea rdi,[rel request]
 mov ecx,NEBOC_BIND_REQUEST_SIZE/8
 xor eax,eax
 rep stosq
 mov qword [rel request+NEBOC_BIND_OPERATION_OFFSET],NEBOC_BIND_OP_TYPED_DECLARATION
 mov qword [rel request+NEBOC_BIND_DECLARED_TYPE_OFFSET],NEBOC_BIND_TYPE_INT
 mov qword [rel request+NEBOC_BIND_SYMBOL_STATE_OFFSET],NEBOC_BIND_STATE_ABSENT
 mov qword [rel request+NEBOC_BIND_INPUT_FLAGS_OFFSET],NEBOC_BIND_INPUT_VALID_NAME
 lea rax,[rel n_counter]
 mov [rel request+NEBOC_BIND_NAME_PTR_OFFSET],rax
 mov qword [rel request+NEBOC_BIND_NAME_LENGTH_OFFSET],7
 lea rdi,[rel request]
 call neboc_binding_contract
 test eax,eax
 jnz .fail
 mov rax,[rel request+NEBOC_BIND_HASH_OFFSET]
 mov [rel first_hash],rax
 lea rdi,[rel request]
 call neboc_binding_contract
 test eax,eax
 jnz .fail
 mov rax,[rel first_hash]
 cmp rax,[rel request+NEBOC_BIND_HASH_OFFSET]
 jne .fail
 xor edi,edi
 call neboc_binding_contract
 cmp eax,NEBOC_STATUS_INVALID_ARGUMENT
 jne .fail
 xor edi,edi
 jmp neboc_host_process_exit
.fail:
 mov edi,r13d
 jmp neboc_host_process_exit
section .note.GNU-stack noalloc noexec nowrite progbits
