; Nebo Assembly — MF026 intrinsic signatures and runtime contracts
bits 64
default rel

%include "compiler/abi/internal/x86_64/neboc_internal_abi.inc"
%include "compiler/support/status/status_codes.inc"
%include "compiler/semantic/types/type_table.inc"
%include "compiler/semantic/effect/effect_classifier.inc"
%include "compiler/semantic/behavior/behavior_table.inc"
%include "compiler/semantic/intrinsic/intrinsic_table.inc"

section .text

; intrinsic_table_init(table*, entries*, capacity)
NEBOC_ABI_FUNCTION neboc_intrinsic_table_init
 test rdi,rdi
 jz .invalid
 test rsi,rsi
 jz .invalid
 cmp rdx,NEBOC_INTRINSIC_COUNT
 jb .invalid
 mov [rdi+NEBOC_INTRINSIC_TABLE_DATA_OFFSET],rsi
 mov qword [rdi+NEBOC_INTRINSIC_TABLE_COUNT_OFFSET],0
 mov [rdi+NEBOC_INTRINSIC_TABLE_CAPACITY_OFFSET],rdx
 mov qword [rdi+NEBOC_INTRINSIC_TABLE_STATE_OFFSET],NEBOC_INTRINSIC_TABLE_STATE_MUTABLE
 mov qword [rdi+NEBOC_INTRINSIC_TABLE_HASH_OFFSET],0
 mov qword [rdi+NEBOC_INTRINSIC_TABLE_RUNTIME_VERSION_OFFSET],NEBOC_RUNTIME_CONTRACT_VERSION_V0_1
 NEBOC_ABI_RETURN_STATUS NEBOC_STATUS_OK
.invalid:
 NEBOC_ABI_RETURN_STATUS NEBOC_STATUS_INVALID_ARGUMENT

; intrinsic_table_declare_v0_1(table*)
NEBOC_ABI_FUNCTION neboc_intrinsic_table_declare_v0_1
 push rbx
 push r12
 mov r12,rdi
 test r12,r12
 jz .declare_invalid
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_STATE_OFFSET],NEBOC_INTRINSIC_TABLE_STATE_MUTABLE
 jne .declare_invalid
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_CAPACITY_OFFSET],NEBOC_INTRINSIC_COUNT
 jb .declare_limit
 mov rbx,[r12+NEBOC_INTRINSIC_TABLE_DATA_OFFSET]
 test rbx,rbx
 jz .declare_invalid

 ; Text.console() -> Console
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ID_OFFSET],NEBOC_INTRINSIC_ID_TEXT_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_KIND_OFFSET],NEBOC_INTRINSIC_KIND_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],NEBOC_INTRINSIC_NAME_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RECEIVER_TYPE_OFFSET],NEBOC_TYPE_ID_TEXT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RETURN_TYPE_OFFSET],NEBOC_TYPE_ID_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_EFFECT_ID_OFFSET],NEBOC_EFFECT_ID_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_CONCURRENCY_OFFSET],NEBOC_INTRINSIC_CONCURRENCY_THREAD_CAPABLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ACCEPTED_BEHAVIOR_MASK_OFFSET],NEBOC_BEHAVIOR_MASK_COLOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_TEXT_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_POSITIONAL_COUNT_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_FLAGS_OFFSET],NEBOC_INTRINSIC_FLAG_NORMAL_CALL | NEBOC_INTRINSIC_FLAG_SPECIAL_SEMANTICS | NEBOC_INTRINSIC_FLAG_ACCEPTS_BEHAVIORS
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_SIGNATURE_HASH_OFFSET],0

 ; Int.console() -> Console
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ID_OFFSET],NEBOC_INTRINSIC_ID_INT_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_KIND_OFFSET],NEBOC_INTRINSIC_KIND_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],NEBOC_INTRINSIC_NAME_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RECEIVER_TYPE_OFFSET],NEBOC_TYPE_ID_INT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RETURN_TYPE_OFFSET],NEBOC_TYPE_ID_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_EFFECT_ID_OFFSET],NEBOC_EFFECT_ID_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_CONCURRENCY_OFFSET],NEBOC_INTRINSIC_CONCURRENCY_THREAD_CAPABLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ACCEPTED_BEHAVIOR_MASK_OFFSET],NEBOC_BEHAVIOR_MASK_COLOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_INT_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_POSITIONAL_COUNT_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_FLAGS_OFFSET],NEBOC_INTRINSIC_FLAG_NORMAL_CALL | NEBOC_INTRINSIC_FLAG_SPECIAL_SEMANTICS | NEBOC_INTRINSIC_FLAG_ACCEPTS_BEHAVIORS
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_SIGNATURE_HASH_OFFSET],0

 ; Bool.console() -> Console
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ID_OFFSET],NEBOC_INTRINSIC_ID_BOOL_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_KIND_OFFSET],NEBOC_INTRINSIC_KIND_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],NEBOC_INTRINSIC_NAME_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RECEIVER_TYPE_OFFSET],NEBOC_TYPE_ID_BOOL
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RETURN_TYPE_OFFSET],NEBOC_TYPE_ID_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_EFFECT_ID_OFFSET],NEBOC_EFFECT_ID_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_CONCURRENCY_OFFSET],NEBOC_INTRINSIC_CONCURRENCY_THREAD_CAPABLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ACCEPTED_BEHAVIOR_MASK_OFFSET],NEBOC_BEHAVIOR_MASK_COLOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_BOOL_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_POSITIONAL_COUNT_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_FLAGS_OFFSET],NEBOC_INTRINSIC_FLAG_NORMAL_CALL | NEBOC_INTRINSIC_FLAG_SPECIAL_SEMANTICS | NEBOC_INTRINSIC_FLAG_ACCEPTS_BEHAVIORS
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_SIGNATURE_HASH_OFFSET],0

 ; Text.scan() -> Pending<Text>
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ID_OFFSET],NEBOC_INTRINSIC_ID_TEXT_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_KIND_OFFSET],NEBOC_INTRINSIC_KIND_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],NEBOC_INTRINSIC_NAME_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RECEIVER_TYPE_OFFSET],NEBOC_TYPE_ID_TEXT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RETURN_TYPE_OFFSET],NEBOC_TYPE_ID_PENDING_TEXT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_EFFECT_ID_OFFSET],NEBOC_EFFECT_ID_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_CONCURRENCY_OFFSET],NEBOC_INTRINSIC_CONCURRENCY_THREAD_CAPABLE | NEBOC_INTRINSIC_CONCURRENCY_PENDING_RESULT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ACCEPTED_BEHAVIOR_MASK_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_TEXT_SCAN_DEFAULT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_POSITIONAL_COUNT_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_FLAGS_OFFSET],NEBOC_INTRINSIC_FLAG_NORMAL_CALL | NEBOC_INTRINSIC_FLAG_SPECIAL_SEMANTICS | NEBOC_INTRINSIC_FLAG_PENDING_RESULT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_SIGNATURE_HASH_OFFSET],0

 ; Console.scan() -> Pending<Text>
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ID_OFFSET],NEBOC_INTRINSIC_ID_CONSOLE_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_KIND_OFFSET],NEBOC_INTRINSIC_KIND_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],NEBOC_INTRINSIC_NAME_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RECEIVER_TYPE_OFFSET],NEBOC_TYPE_ID_CONSOLE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RETURN_TYPE_OFFSET],NEBOC_TYPE_ID_PENDING_TEXT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_EFFECT_ID_OFFSET],NEBOC_EFFECT_ID_SCAN
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_CONCURRENCY_OFFSET],NEBOC_INTRINSIC_CONCURRENCY_THREAD_CAPABLE | NEBOC_INTRINSIC_CONCURRENCY_PENDING_RESULT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ACCEPTED_BEHAVIOR_MASK_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_CONSOLE_SCAN_INLINE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_POSITIONAL_COUNT_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_FLAGS_OFFSET],NEBOC_INTRINSIC_FLAG_NORMAL_CALL | NEBOC_INTRINSIC_FLAG_SPECIAL_SEMANTICS | NEBOC_INTRINSIC_FLAG_PENDING_RESULT
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_SIGNATURE_HASH_OFFSET],0

 ; Color.color() -> Behavior<ForegroundColor>
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ID_OFFSET],NEBOC_INTRINSIC_ID_COLOR_BEHAVIOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_KIND_OFFSET],NEBOC_INTRINSIC_KIND_COLOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],NEBOC_INTRINSIC_NAME_COLOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RECEIVER_TYPE_OFFSET],NEBOC_TYPE_ID_COLOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RETURN_TYPE_OFFSET],NEBOC_TYPE_ID_BEHAVIOR_FOREGROUND_COLOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_EFFECT_ID_OFFSET],NEBOC_EFFECT_ID_PURE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_CONCURRENCY_OFFSET],NEBOC_INTRINSIC_CONCURRENCY_NONE
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_ACCEPTED_BEHAVIOR_MASK_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_COLOR_FOREGROUND_DESCRIPTOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_POSITIONAL_COUNT_OFFSET],0
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_FLAGS_OFFSET],NEBOC_INTRINSIC_FLAG_NORMAL_CALL | NEBOC_INTRINSIC_FLAG_DESCRIPTOR
 mov qword [rbx+NEBOC_INTRINSIC_ENTRY_SIGNATURE_HASH_OFFSET],0

 mov qword [r12+NEBOC_INTRINSIC_TABLE_COUNT_OFFSET],NEBOC_INTRINSIC_COUNT
 xor eax,eax
 jmp .declare_done
.declare_limit:
 mov eax,NEBOC_STATUS_LIMIT_EXCEEDED
 jmp .declare_done
.declare_invalid:
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
.declare_done:
 pop r12
 pop rbx
 cld
 ret

; intrinsic_table_get(table*, intrinsic_id, out_entry_ptr*)
NEBOC_ABI_FUNCTION neboc_intrinsic_table_get
 test rdi,rdi
 jz .get_invalid
 test rdx,rdx
 jz .get_invalid
 mov qword [rdx],0
 test rsi,rsi
 jz .get_invalid
 cmp rsi,[rdi+NEBOC_INTRINSIC_TABLE_COUNT_OFFSET]
 ja .get_invalid
 mov rax,rsi
 dec rax
 imul rax,NEBOC_INTRINSIC_ENTRY_SIZE
 add rax,[rdi+NEBOC_INTRINSIC_TABLE_DATA_OFFSET]
 mov [rdx],rax
 NEBOC_ABI_RETURN_STATUS NEBOC_STATUS_OK
.get_invalid:
 NEBOC_ABI_RETURN_STATUS NEBOC_STATUS_INVALID_ARGUMENT

; intrinsic_table_freeze(table*)
NEBOC_ABI_FUNCTION neboc_intrinsic_table_freeze
 push rbx
 push r12
 push r13
 push r14
 mov r12,rdi
 test r12,r12
 jz .freeze_invalid
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_STATE_OFFSET],NEBOC_INTRINSIC_TABLE_STATE_MUTABLE
 jne .freeze_invalid
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_COUNT_OFFSET],NEBOC_INTRINSIC_COUNT
 jne .freeze_invalid
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_RUNTIME_VERSION_OFFSET],NEBOC_RUNTIME_CONTRACT_VERSION_V0_1
 jne .freeze_invalid
 mov r13,[r12+NEBOC_INTRINSIC_TABLE_DATA_OFFSET]
 test r13,r13
 jz .freeze_invalid
 mov ebx,NEBOC_INTRINSIC_HASH_FNV1A32_OFFSET_BASIS
 xor r14d,r14d
.entry_loop:
 cmp r14,NEBOC_INTRINSIC_COUNT
 jae .freeze_done_hash
 mov rax,r14
 imul rax,NEBOC_INTRINSIC_ENTRY_SIZE
 add rax,r13
 mov ecx,11
 mov r8,rax
 mov r9d,NEBOC_INTRINSIC_HASH_FNV1A32_OFFSET_BASIS
.entry_hash_loop:
 mov rdx,[r8]
 push rcx
 mov ecx,8
.entry_hash_bytes:
 movzx r10d,dl
 xor r9d,r10d
 imul r9d,r9d,NEBOC_INTRINSIC_HASH_FNV1A32_PRIME
 shr rdx,8
 dec ecx
 jnz .entry_hash_bytes
 pop rcx
 add r8,8
 dec ecx
 jnz .entry_hash_loop
 mov [rax+NEBOC_INTRINSIC_ENTRY_SIGNATURE_HASH_OFFSET],r9
 xor ebx,r9d
 imul ebx,ebx,NEBOC_INTRINSIC_HASH_FNV1A32_PRIME
 inc r14
 jmp .entry_loop
.freeze_done_hash:
 mov [r12+NEBOC_INTRINSIC_TABLE_HASH_OFFSET],rbx
 mov qword [r12+NEBOC_INTRINSIC_TABLE_STATE_OFFSET],NEBOC_INTRINSIC_TABLE_STATE_FROZEN
 xor eax,eax
 jmp .freeze_done
.freeze_invalid:
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
.freeze_done:
 pop r14
 pop r13
 pop r12
 pop rbx
 cld
 ret

; intrinsic_table_validate_runtime_contracts(table*)
NEBOC_ABI_FUNCTION neboc_intrinsic_table_validate_runtime_contracts
 push rbx
 push r12
 mov r12,rdi
 test r12,r12
 jz .contracts_invalid
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_STATE_OFFSET],NEBOC_INTRINSIC_TABLE_STATE_FROZEN
 jne .contracts_invalid
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_RUNTIME_VERSION_OFFSET],NEBOC_RUNTIME_CONTRACT_VERSION_V0_1
 jne .contracts_invalid
 mov rbx,[r12+NEBOC_INTRINSIC_TABLE_DATA_OFFSET]
 test rbx,rbx
 jz .contracts_invalid
 cmp qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_TEXT_CONSOLE
 jne .contracts_invalid
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 cmp qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_INT_CONSOLE
 jne .contracts_invalid
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 cmp qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_BOOL_CONSOLE
 jne .contracts_invalid
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 cmp qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_TEXT_SCAN_DEFAULT
 jne .contracts_invalid
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 cmp qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_CONSOLE_SCAN_INLINE
 jne .contracts_invalid
 add rbx,NEBOC_INTRINSIC_ENTRY_SIZE
 cmp qword [rbx+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET],NEBOC_RUNTIME_CONTRACT_COLOR_FOREGROUND_DESCRIPTOR
 jne .contracts_invalid
 xor eax,eax
 jmp .contracts_done
.contracts_invalid:
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
.contracts_done:
 pop r12
 pop rbx
 cld
 ret

; intrinsic_resolve(table*, request*)
; Normal signature matching occurs first. Runtime-special semantics are returned
; as explicit metadata only after a unique receiver/name/arity match.
NEBOC_ABI_FUNCTION neboc_intrinsic_resolve
 push rbx
 push r12
 push r13
 push r14
 push r15
 mov r12,rdi
 mov r13,rsi
 test r12,r12
 jz .bad_argument
 test r13,r13
 jz .bad_argument
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_OUT_INTRINSIC_ID_OFFSET],0
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_OUT_RETURN_TYPE_OFFSET],0
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_OUT_EFFECT_ID_OFFSET],0
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_OUT_CONCURRENCY_OFFSET],0
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_OUT_RUNTIME_CONTRACT_OFFSET],0
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_OUT_FLAGS_OFFSET],0
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_ERROR_CODE_OFFSET],NEBOC_INTRINSIC_ERROR_NONE
 cmp qword [r12+NEBOC_INTRINSIC_TABLE_STATE_OFFSET],NEBOC_INTRINSIC_TABLE_STATE_FROZEN
 jne .bad_table
 mov rbx,[r12+NEBOC_INTRINSIC_TABLE_DATA_OFFSET]
 test rbx,rbx
 jz .bad_table
 xor r14d,r14d
 xor r15d,r15d
.search:
 cmp r14,[r12+NEBOC_INTRINSIC_TABLE_COUNT_OFFSET]
 jae .search_done
 mov rax,r14
 imul rax,NEBOC_INTRINSIC_ENTRY_SIZE
 add rax,rbx
 cmp qword [rax+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],0
 je .next
 mov rcx,[r13+NEBOC_INTRINSIC_REQUEST_NAME_ID_OFFSET]
 cmp [rax+NEBOC_INTRINSIC_ENTRY_NAME_ID_OFFSET],rcx
 jne .next
 mov rcx,[r13+NEBOC_INTRINSIC_REQUEST_RECEIVER_TYPE_OFFSET]
 cmp [rax+NEBOC_INTRINSIC_ENTRY_RECEIVER_TYPE_OFFSET],rcx
 jne .next
 mov rcx,[r13+NEBOC_INTRINSIC_REQUEST_POSITIONAL_COUNT_OFFSET]
 cmp [rax+NEBOC_INTRINSIC_ENTRY_POSITIONAL_COUNT_OFFSET],rcx
 jne .next
 test r15,r15
 jnz .ambiguous
 mov r15,rax
.next:
 inc r14
 jmp .search
.search_done:
 test r15,r15
 jz .no_match
 mov rax,[r13+NEBOC_INTRINSIC_REQUEST_BEHAVIOR_MASK_OFFSET]
 mov rcx,[r15+NEBOC_INTRINSIC_ENTRY_ACCEPTED_BEHAVIOR_MASK_OFFSET]
 not rcx
 and rax,rcx
 test rax,rax
 jnz .unsupported_behavior
 mov rax,[r15+NEBOC_INTRINSIC_ENTRY_ID_OFFSET]
 mov [r13+NEBOC_INTRINSIC_REQUEST_OUT_INTRINSIC_ID_OFFSET],rax
 mov rax,[r15+NEBOC_INTRINSIC_ENTRY_RETURN_TYPE_OFFSET]
 mov [r13+NEBOC_INTRINSIC_REQUEST_OUT_RETURN_TYPE_OFFSET],rax
 mov rax,[r15+NEBOC_INTRINSIC_ENTRY_EFFECT_ID_OFFSET]
 mov [r13+NEBOC_INTRINSIC_REQUEST_OUT_EFFECT_ID_OFFSET],rax
 mov rax,[r15+NEBOC_INTRINSIC_ENTRY_CONCURRENCY_OFFSET]
 mov [r13+NEBOC_INTRINSIC_REQUEST_OUT_CONCURRENCY_OFFSET],rax
 mov rax,[r15+NEBOC_INTRINSIC_ENTRY_RUNTIME_CONTRACT_ID_OFFSET]
 mov [r13+NEBOC_INTRINSIC_REQUEST_OUT_RUNTIME_CONTRACT_OFFSET],rax
 mov rax,[r15+NEBOC_INTRINSIC_ENTRY_FLAGS_OFFSET]
 mov [r13+NEBOC_INTRINSIC_REQUEST_OUT_FLAGS_OFFSET],rax
 xor eax,eax
 jmp .done
.no_match:
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_ERROR_CODE_OFFSET],NEBOC_INTRINSIC_ERROR_NO_MATCH
 mov eax,NEBOC_STATUS_INVALID_SOURCE
 jmp .done
.unsupported_behavior:
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_ERROR_CODE_OFFSET],NEBOC_INTRINSIC_ERROR_UNSUPPORTED_BEHAVIOR
 mov eax,NEBOC_STATUS_INVALID_SOURCE
 jmp .done
.ambiguous:
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_ERROR_CODE_OFFSET],NEBOC_INTRINSIC_ERROR_AMBIGUOUS
 mov eax,NEBOC_STATUS_INTERNAL_ERROR
 jmp .done
.bad_table:
 mov qword [r13+NEBOC_INTRINSIC_REQUEST_ERROR_CODE_OFFSET],NEBOC_INTRINSIC_ERROR_BAD_TABLE
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
 jmp .done
.bad_argument:
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
.done:
 pop r15
 pop r14
 pop r13
 pop r12
 pop rbx
 cld
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
