; Generated deterministically from the eleven core_operator_tokens_tokens P01 Registry rows.
bits 64
default rel

%include "compiler/abi/internal/x86_64/neboc_internal_abi.inc"
%include "compiler/tokens/token_kind.inc"
%include "compiler/tokens/operator_registry.inc"

section .rodata
lex_dot: db '.'
lex_lparen: db '('
lex_rparen: db ')'
lex_lbrace: db '{'
lex_rbrace: db '}'
lex_lbracket: db '['
lex_rbracket: db ']'
lex_less: db '<'
lex_greater: db '>'
lex_comma: db ','
lex_semicolon: db ';'
lex_colon: db ':'
lex_arrow: db '->'
lex_underscore: db '_'
lex_line_comment: db '//'

align 8
operator_entries:
; id, class, state, contexts, fixity, precedence, assoc, lexeme start/count, domain, flags
dq 1,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_EXPRESSION|NEBOC_OPERATOR_CONTEXT_BINDING,NEBOC_OPERATOR_FIXITY_CONTEXTUAL,180,NEBOC_OPERATOR_ASSOC_CONTEXTUAL,0,1,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_CONTEXTUAL
dq 2,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_EXPRESSION|NEBOC_OPERATOR_CONTEXT_ARGUMENT,NEBOC_OPERATOR_FIXITY_DELIMITED,180,NEBOC_OPERATOR_ASSOC_LEFT,1,2,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_NO_OVERLOAD
dq 3,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_BODY|NEBOC_OPERATOR_CONTEXT_STATEMENT,NEBOC_OPERATOR_FIXITY_DELIMITED,0,NEBOC_OPERATOR_ASSOC_NONE,3,2,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_NO_OVERLOAD
dq 4,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_PARTIAL_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_EXPRESSION|NEBOC_OPERATOR_CONTEXT_TYPE,NEBOC_OPERATOR_FIXITY_DELIMITED,180,NEBOC_OPERATOR_ASSOC_CONTEXTUAL,5,2,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_CONTEXTUAL
dq 5,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_TYPE|NEBOC_OPERATOR_CONTEXT_EXPRESSION,NEBOC_OPERATOR_FIXITY_CONTEXTUAL,0,NEBOC_OPERATOR_ASSOC_CONTEXTUAL,7,2,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_CONTEXTUAL
dq 6,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_ARGUMENT|NEBOC_OPERATOR_CONTEXT_TYPE,NEBOC_OPERATOR_FIXITY_SEPARATOR,0,NEBOC_OPERATOR_ASSOC_NONE,9,1,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_NO_OVERLOAD
dq 7,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_STATEMENT,NEBOC_OPERATOR_FIXITY_TERMINATOR,0,NEBOC_OPERATOR_ASSOC_NONE,10,1,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_NO_OVERLOAD
dq 8,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_TYPE|NEBOC_OPERATOR_CONTEXT_ARGUMENT,NEBOC_OPERATOR_FIXITY_CONTEXTUAL,0,NEBOC_OPERATOR_ASSOC_CONTEXTUAL,11,1,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_CONTEXTUAL|NEBOC_OPERATOR_FLAG_NO_OVERLOAD
dq 9,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_TYPE|NEBOC_OPERATOR_CONTEXT_PATTERN,NEBOC_OPERATOR_FIXITY_CONTEXTUAL,0,NEBOC_OPERATOR_ASSOC_RIGHT,12,1,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_CONTEXTUAL|NEBOC_OPERATOR_FLAG_NO_OVERLOAD
dq 10,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_PATTERN|NEBOC_OPERATOR_CONTEXT_BINDING,NEBOC_OPERATOR_FIXITY_ATOMIC,0,NEBOC_OPERATOR_ASSOC_NONE,13,1,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_CONTEXTUAL|NEBOC_OPERATOR_FLAG_NO_OVERLOAD
dq 11,NEBOC_OPERATOR_CLASS_CORE_ALWAYS_ON,NEBOC_OPERATOR_STATE_ACTIVE_CURRENT
dq NEBOC_OPERATOR_CONTEXT_LEXICAL,NEBOC_OPERATOR_FIXITY_LEXICAL,0,NEBOC_OPERATOR_ASSOC_NONE,14,1,NEBOC_OPERATOR_DOMAIN_CORE,NEBOC_OPERATOR_FLAG_SKIP_TOKEN|NEBOC_OPERATOR_FLAG_NO_OVERLOAD

align 8
operator_lexemes:
; bytes, byte length, code points, token kind, Registry ID, token flags
dq lex_dot,1,1,NEBOC_TOKEN_DOT,1,NEBOC_TOKEN_FLAG_NONE
dq lex_lparen,1,1,NEBOC_TOKEN_LPAREN,2,NEBOC_TOKEN_FLAG_NONE
dq lex_rparen,1,1,NEBOC_TOKEN_RPAREN,2,NEBOC_TOKEN_FLAG_NONE
dq lex_lbrace,1,1,NEBOC_TOKEN_LBRACE,3,NEBOC_TOKEN_FLAG_NONE
dq lex_rbrace,1,1,NEBOC_TOKEN_RBRACE,3,NEBOC_TOKEN_FLAG_NONE
dq lex_lbracket,1,1,NEBOC_TOKEN_RESERVED_LBRACKET,4,NEBOC_TOKEN_FLAG_RESERVED
dq lex_rbracket,1,1,NEBOC_TOKEN_RESERVED_RBRACKET,4,NEBOC_TOKEN_FLAG_RESERVED
dq lex_less,1,1,NEBOC_TOKEN_LESS,5,NEBOC_TOKEN_FLAG_NONE
dq lex_greater,1,1,NEBOC_TOKEN_GREATER,5,NEBOC_TOKEN_FLAG_NONE
dq lex_comma,1,1,NEBOC_TOKEN_COMMA,6,NEBOC_TOKEN_FLAG_NONE
dq lex_semicolon,1,1,NEBOC_TOKEN_SEMICOLON,7,NEBOC_TOKEN_FLAG_NONE
dq lex_colon,1,1,NEBOC_TOKEN_RESERVED_COLON,8,NEBOC_TOKEN_FLAG_RESERVED
dq lex_arrow,2,2,NEBOC_TOKEN_RESERVED_ARROW,9,NEBOC_TOKEN_FLAG_RESERVED
dq lex_underscore,1,1,NEBOC_TOKEN_IDENTIFIER,10,NEBOC_TOKEN_FLAG_NONE
dq lex_line_comment,2,2,NEBOC_TOKEN_INVALID,11,NEBOC_TOKEN_FLAG_NONE

section .text
; Return RAX=table, RDX=count, RCX=schema version.
NEBOC_ABI_FUNCTION neboc_operator_registry_entry_table
 lea rax,[rel operator_entries]
 mov edx,NEBOC_OPERATOR_REGISTRY_ENTRY_COUNT
 mov ecx,NEBOC_OPERATOR_REGISTRY_SCHEMA_VERSION
 ret

; Return RAX=table, RDX=count, RCX=schema version.
NEBOC_ABI_FUNCTION neboc_operator_registry_lexeme_table
 lea rax,[rel operator_lexemes]
 mov edx,NEBOC_OPERATOR_REGISTRY_LEXEME_COUNT
 mov ecx,NEBOC_OPERATOR_REGISTRY_SCHEMA_VERSION
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
