; Nebo Assembly — SEGURANCA-NUMERICA-CONVERSOES-E-OVERFLOW-PF004 isolated numeric-safety native lowering prototype
bits 64
default rel

%include "compiler/abi/internal/x86_64/neboc_internal_abi.inc"
%include "compiler/support/status/status_codes.inc"
%include "compiler/semantic/types/type_table.inc"
%include "compiler/parser/numeric_safety_api_contract.inc"
%include "compiler/semantic/types/numeric_safety_semantic.inc"
%include "compiler/lowering/scalars/numeric_safety_ir_contract.inc"
%include "compiler/lowering/scalars/numeric_safety_native_lowering.inc"

section .text

; neboc_numeric_safety_native_lower(request*) -> StatusCode
; Selects only the certified x86-64 System V representation, ABI registers,
; SSE2/bitwise operation class and isolated runtime helper. PF004 emits no
; public compiler code and does not connect this plan to neboc.
NEBOC_ABI_FUNCTION neboc_numeric_safety_native_lower
 push r12
 push r13
 push r14
 sub rsp,8
 mov r12,rdi
 test r12,r12
 jz .invalid_argument
 mov r13,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_SEMANTIC_REQUEST_OFFSET]
 mov r14,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_IR_REQUEST_OFFSET]
 test r13,r13
 jz .invalid_argument
 test r14,r14
 jz .invalid_argument
 lea rdi,[r12+NEBOC_NATIVE_METHOD_ID_OFFSET]
 mov ecx,(neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_REQUEST_SIZE-NEBOC_NATIVE_METHOD_ID_OFFSET)/8
 xor eax,eax
 rep stosq
 cmp qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_TARGET_ID_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_TARGET_X86_64_SYSTEMV_ELF_LINUX
 jne .target_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_ERROR_CODE_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_SEM_ERROR_NONE
 jne .semantic_invalid
 cmp qword [r14+neboc_seguranca_numerica_conversoes_e_overflow_IR_ERROR_CODE_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_IR_ERROR_NONE
 jne .ir_invalid
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_RUNTIME_METADATA_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_SEM_RUNTIME_METADATA_NONE
 jne .metadata_error
 cmp qword [r14+neboc_seguranca_numerica_conversoes_e_overflow_IR_RUNTIME_METADATA_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_IR_RUNTIME_METADATA_NONE
 jne .metadata_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_SEMANTIC_HASH_OFFSET],0
 je .contract_error
 cmp qword [r14+neboc_seguranca_numerica_conversoes_e_overflow_IR_HASH_OFFSET],0
 je .contract_error

 mov rax,[r13+NEBOC_SEM_METHOD_ID_OFFSET]
 cmp rax,[r14+NEBOC_IR_HIR_OPERATION_OFFSET]
 jne .contract_error
 cmp rax,NEBOC_API_METHOD_INT_TO_FLOAT
 je .conversion
 cmp rax,NEBOC_API_METHOD_FLOAT_IS_FINITE
 jb .method_error
 cmp rax,NEBOC_API_METHOD_FLOAT_IS_NEGATIVE_ZERO
 ja .method_error
 jmp .classifier

.conversion:
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEMANTIC_KIND_OFFSET],NEBOC_SEM_KIND_CONVERSION
 jne .contract_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_OPERAND_TYPE_OFFSET],NEBOC_TYPE_ID_INT
 jne .contract_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_RESULT_TYPE_OFFSET],NEBOC_TYPE_ID_FLOAT
 jne .contract_error
 cmp qword [r13+NEBOC_SEM_CONVERSION_POLICY_OFFSET],NEBOC_SEM_CONVERSION_I64_TO_F64_ROUND_TIES_EVEN
 jne .contract_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_LIR_KIND_OFFSET],NEBOC_SEM_LIR_ABSTRACT_I64_TO_F64
 jne .contract_error
 cmp qword [r14+neboc_seguranca_numerica_conversoes_e_overflow_IR_LIR_KIND_OFFSET],NEBOC_IR_LIR_ABSTRACT_I64_TO_F64
 jne .contract_error
 cmp qword [r14+NEBOC_IR_LIR_OPERAND_REPR_OFFSET],NEBOC_IR_REPR_SIGNED_I64
 jne .contract_error
 cmp qword [r14+NEBOC_IR_LIR_RESULT_REPR_OFFSET],NEBOC_IR_REPR_IEEE_BINARY64_BITS
 jne .contract_error
 cmp qword [r14+NEBOC_IR_LIR_POLICY_OFFSET],NEBOC_SEM_CONVERSION_I64_TO_F64_ROUND_TIES_EVEN
 jne .contract_error
 mov qword [r12+NEBOC_NATIVE_OPERATION_KIND_OFFSET],NEBOC_NATIVE_OPERATION_CONVERSION
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_TYPE_OFFSET],NEBOC_TYPE_ID_INT
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_TYPE_OFFSET],NEBOC_TYPE_ID_FLOAT
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_REPR_OFFSET],NEBOC_IR_REPR_SIGNED_I64
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_REPR_OFFSET],NEBOC_IR_REPR_IEEE_BINARY64_BITS
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_ABI_CLASS_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ABI_CLASS_INTEGER
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_ABI_CLASS_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ABI_CLASS_SSE
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_PARAMETER_REGISTER_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_REGISTER_RDI
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RETURN_REGISTER_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_REGISTER_XMM0
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_INSTRUCTION_OFFSET],NEBOC_NATIVE_INSTRUCTION_CVTSI2SD_XMM_R64
 mov qword [r12+NEBOC_NATIVE_ROUNDING_MODE_OFFSET],NEBOC_NATIVE_ROUNDING_MXCSR_RN_TIES_EVEN
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RUNTIME_HELPER_OFFSET],NEBOC_NATIVE_HELPER_INT_TO_FLOAT
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_SCRATCH_SIZE_OFFSET],16
 mov qword [r12+NEBOC_NATIVE_SCRATCH_ALIGNMENT_OFFSET],4
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_FLAGS_OFFSET],NEBOC_NATIVE_FLAGS_CONVERSION
 jmp .finish

.classifier:
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEMANTIC_KIND_OFFSET],NEBOC_SEM_KIND_CLASSIFIER
 jne .contract_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_OPERAND_TYPE_OFFSET],NEBOC_TYPE_ID_FLOAT
 jne .contract_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_RESULT_TYPE_OFFSET],NEBOC_TYPE_ID_BOOL
 jne .contract_error
 cmp qword [r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_LIR_KIND_OFFSET],NEBOC_SEM_LIR_ABSTRACT_F64_CLASSIFY
 jne .contract_error
 cmp qword [r14+neboc_seguranca_numerica_conversoes_e_overflow_IR_LIR_KIND_OFFSET],NEBOC_IR_LIR_ABSTRACT_F64_CLASSIFY
 jne .contract_error
 cmp qword [r14+NEBOC_IR_LIR_OPERAND_REPR_OFFSET],NEBOC_IR_REPR_IEEE_BINARY64_BITS
 jne .contract_error
 cmp qword [r14+NEBOC_IR_LIR_RESULT_REPR_OFFSET],NEBOC_IR_REPR_CANONICAL_BOOL
 jne .contract_error
 mov rax,[r13+NEBOC_SEM_METHOD_ID_OFFSET]
 dec rax
 cmp rax,[r13+NEBOC_SEM_CLASSIFIER_KIND_OFFSET]
 jne .contract_error
 cmp rax,[r14+NEBOC_IR_LIR_POLICY_OFFSET]
 jne .contract_error
 mov qword [r12+NEBOC_NATIVE_OPERATION_KIND_OFFSET],NEBOC_NATIVE_OPERATION_CLASSIFIER
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_TYPE_OFFSET],NEBOC_TYPE_ID_FLOAT
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_TYPE_OFFSET],NEBOC_TYPE_ID_BOOL
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_REPR_OFFSET],NEBOC_IR_REPR_IEEE_BINARY64_BITS
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_REPR_OFFSET],NEBOC_IR_REPR_CANONICAL_BOOL
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_ABI_CLASS_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ABI_CLASS_SSE
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_ABI_CLASS_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ABI_CLASS_INTEGER
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_PARAMETER_REGISTER_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_REGISTER_XMM0
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RETURN_REGISTER_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_REGISTER_RAX
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_INSTRUCTION_OFFSET],NEBOC_NATIVE_INSTRUCTION_BITWISE_F64_CLASSIFY
 mov qword [r12+NEBOC_NATIVE_ROUNDING_MODE_OFFSET],NEBOC_NATIVE_ROUNDING_NONE
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_SCRATCH_SIZE_OFFSET],0
 mov qword [r12+NEBOC_NATIVE_SCRATCH_ALIGNMENT_OFFSET],1
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_FLAGS_OFFSET],NEBOC_NATIVE_FLAGS_CLASSIFIER
 mov rax,[r13+NEBOC_SEM_METHOD_ID_OFFSET]
 mov [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RUNTIME_HELPER_OFFSET],rax

.finish:
 mov rax,[r13+NEBOC_SEM_METHOD_ID_OFFSET]
 mov [r12+NEBOC_NATIVE_METHOD_ID_OFFSET],rax
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RUNTIME_METADATA_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RUNTIME_METADATA_NONE
 mov rax,[r13+neboc_seguranca_numerica_conversoes_e_overflow_SEM_SEMANTIC_HASH_OFFSET]
 mov [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_SEMANTIC_HASH_OFFSET],rax
 mov rax,[r14+neboc_seguranca_numerica_conversoes_e_overflow_IR_HASH_OFFSET]
 mov [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_IR_HASH_OFFSET],rax

 ; Native plan hash intentionally excludes source provenance, spans and operand value bits.
 mov rax,1469598103934665603
 mov rcx,1099511628211
 xor rax,[r12+NEBOC_NATIVE_METHOD_ID_OFFSET]
 imul rax,rcx
 xor rax,[r12+NEBOC_NATIVE_OPERATION_KIND_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_TYPE_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_TYPE_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_REPR_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_REPR_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_OPERAND_ABI_CLASS_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RESULT_ABI_CLASS_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_PARAMETER_REGISTER_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RETURN_REGISTER_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_INSTRUCTION_OFFSET]
 imul rax,rcx
 xor rax,[r12+NEBOC_NATIVE_ROUNDING_MODE_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_RUNTIME_HELPER_OFFSET]
 imul rax,rcx
 xor rax,[r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_FLAGS_OFFSET]
 imul rax,rcx
 mov [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_HASH_OFFSET],rax
 xor eax,eax
 jmp .done
.semantic_invalid:
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_CODE_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_SEMANTIC_NOT_VALID
 mov eax,NEBOC_STATUS_INVALID_SOURCE
 jmp .done
.ir_invalid:
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_CODE_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_IR_NOT_VALID
 mov eax,NEBOC_STATUS_INVALID_SOURCE
 jmp .done
.target_error:
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_CODE_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_TARGET_UNSUPPORTED
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
 jmp .done
.contract_error:
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_CODE_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_CONTRACT_MISMATCH
 mov eax,NEBOC_STATUS_INTERNAL_ERROR
 jmp .done
.metadata_error:
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_CODE_OFFSET],neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_RUNTIME_METADATA
 mov eax,NEBOC_STATUS_INTERNAL_ERROR
 jmp .done
.method_error:
 mov qword [r12+neboc_seguranca_numerica_conversoes_e_overflow_NATIVE_ERROR_CODE_OFFSET],NEBOC_NATIVE_ERROR_METHOD_UNSUPPORTED
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
 jmp .done
.invalid_argument:
 mov eax,NEBOC_STATUS_INVALID_ARGUMENT
.done:
 add rsp,8
 pop r14
 pop r13
 pop r12
 cld
 ret

section .note.GNU-stack noalloc noexec nowrite progbits
